[project]
name = "gitporter"
version = "1.0.0"
description = "GitPorter 是一个 Git 代码仓批量迁移工具"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "rich>=13.0",
]

[project.scripts]
gitporter = "gitporter.cli:main"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
